function config() {
  return {
    eaName: 'NNFX_V1.0.ex5',
    csvFolderPath: String.raw`C:\Users\LohziIdeaPad3\OneDrive\Documents HDD\Investment\forex\Trading\Backtest\NNFX_V1\V1.0\WalkForward\2021_maxSharpeRatio (2018-2020)\Optimization`,
    backtestResultFolder: String.raw`C:\Users\LohziIdeaPad3\OneDrive\Documents HDD\Investment\forex\Trading\Backtest\NNFX_V1\V1.0\WalkForward\2021_maxSharpeRatio (2018-2020)\Backtest`,
    forwardtestResultFolder: String.raw`C:\Users\LohziIdeaPad3\OneDrive\Documents HDD\Investment\forex\Trading\Backtest\NNFX_V1\V1.0\WalkForward\2021_maxSharpeRatio (2018-2020)\Forwardtest`,
    queueBacktestXmlFolder: String.raw`C:\Users\LohziIdeaPad3\OneDrive\Documents HDD\Investment\forex\Trading\Backtest\NNFX_V1\V1.0\WalkForward\2021_maxSharpeRatio (2018-2020)`,
    csvFileNames: [
      'AUDUSD.csv',
      'EURUSD.csv',
      'USDCAD.csv',
      'USDCHF.csv',
      'USDJPY.csv',
      'GBPUSD.csv',
      'AUDCAD.csv',
      'AUDCHF.csv',
      'AUDNZD.csv',
      'EURAUD.csv',
      'AUDSGD.csv',
      'EURCHF.csv',
      'NZDUSD.csv',
      'EURGBP.csv',
      'GBPAUD.csv',
      'GBPCHF.csv',
      'EURCAD.csv',
      'EURJPY.csv',
      'EURNZD.csv',
      'AUDJPY.csv',
      'CADJPY.csv',
      'CHFJPY.csv',
      'GBPJPY.csv',
      'NZDJPY.csv',
      'GBPCAD.csv',
      'GBPNZD.csv',
      'CADCHF.csv',
      'EURSGD.csv',
      'USDSGD.csv',
      'SGDJPY.csv',
      'GBPSGD.csv',
      'NZDCHF.csv',
      'NZDCAD.csv',
      'CHFSGD.csv',
    ],
    paramNames: [
      'BalanceOfPower_SmoothingPeriod',
      'Ichimoku_Tenkansen',
      'Ichimoku_Kijunsen',
      'TripleJurikSmooth_Period',
      'PriceAndVolumeTrendMovingAverage_Period',
      'RsiWithHann_Period'
    ],
  };
}

export default config;
